<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <title>buoyage_sys</title>
  <script type="text/javascript" src="../baidumapv2/baidumap_offline_v2_load.js"></script>
  <script type="text/javascript" src="/demo/jquery.js"></script> <script type="text/javascript" src="/demo/layer/layer.js"></script>
  <link rel="stylesheet" type="text/css" href="../baidumapv2/css/baidu_map_v2.css"/>
  <link rel="stylesheet" type="text/css" href="/Static/Css/index.css"/>
</head>
<body>
<div id="map_demo">1</div>
<div class="search_bar">
	<div class="search">数据筛选 <img src="/Static/Images/search.png" />
	</div>
	<div class="import">数据导入
		<img src="/Static/Images/import.png" />
	</div>
</div>
</body
</html>
<script type="text/javascript">  
init ();

function init () {
	$(".search_bar .search").bind ("click", function () {
		var search_content = '\
			<div class="layer_search">\
				<div class="title">数据筛选\
					<img src="/Static/Images/search.png" />\
				</div>\
				<div>\
					<span>经度:</span>\
					<input type="text" name="lat" />\
				</div>\
				<div>\
					<span>纬度:</span>\
					<input type="text" name="lon" />\
				</div>\
				<button type="submit">搜索</button>\
			</div>\
		';

		layer.open({
		  type: 1,
		  skin: 'layui-layer-rim', //加上边框
		  area: ['420px', '240px'], //宽高
		  content: search_content
		});
	});

	$(".search_bar .import").bind ("click", function () {
		var search_content = '\
			<form action="/api_main/uploaddata" method="post" enctype="multipart/form-data" >\
			<div class="layer_search">\
				<div class="title">数据导入\
					<img src="/Static/Images/import.png" />\
				</div>\
				<div class="file_upload">\
					<img src="/Static/Images/upload.png" />\
				</div>\
				<input id="real_upload" hidefocus="true" type="file" name="file_upload" accept=".txt" />\
				<button type="submit" class="file_upload_btn">上传</button>\
			</div>\
			</form>\
		';

		layer.open({
		  type: 1,
		  skin: 'layui-layer-rim', //加上边框
		  area: ['420px', '240px'], //宽高
		  content: search_content
		});
	});

	$(".file_upload").die().live("click", function () {
		$("#real_upload").click ();
	});
}

function prepareData () {
	$.getJSON("/api_main/index", function(result){
		var map 	= new BMap.Map("map_demo");
		var datas   = result;	

		map.centerAndZoom(new BMap.Point(100.6,36.202696), 5);
  		map.addControl(new BMap.NavigationControl());

		var colors = ['blue', 'red', 'orange', 'yellow', 'black', 'pink', 'gray', 'green'];
			console.log(points);

		for (i in datas) {
			var lats = datas[i].lats.split(',');		
			var lons = datas[i].lons.split(',');		
			var points   = [];

			for (j in lons) {
				var tmp_lon = lons[j];
				var tmp_lat = lats[j];

				points.push(new BMap.Point(tmp_lon, tmp_lat));
			}

			if (points) {
				var polyline = new BMap.Polyline(points, {strokeColor: colors[i], strokeWeight:2, strokeOpacity:0.5});  //定义折线
			}

			console.log(points);
			map.addOverlay(polyline);     //添加折线到地图上

		}

			var point = new BMap.Point (120, 30);
			var marker = new BMap.Marker(point);
			map.addOverlay(marker);
	});
}

function searchData () {
	
}


prepareData ();
</script>
