<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <title>buoyage_sys</title>
	<style type="text/css">
  body, html,#map_demo, #tab, #mapfrm {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
  #menu{height:100%;overflow-y:auto}
  td{font-size:14px}
  h4{margin:0;}
  #map_demo1,#map_demo2{height: 50%}
  </style>
  <script type="text/javascript" src="../baidumapv2/baidumap_offline_v2_load.js"></script>
  <script type="text/javascript" src="/demo/jquery.js"></script>
  <script type="text/javascript" src="/demo/layer/layer.js"></script>
  <link rel="stylesheet" type="text/css" href="../baidumapv2/css/baidu_map_v2.css"/>
</head>
<body>
<div id="map_demo">1</div>
</body>
</html>
<script type="text/javascript">  
function prepareData () {
	$.getJSON("/api_main/index", function(result){
		var map 	= new BMap.Map("map_demo");
		var datas   = result;	

		map.centerAndZoom(new BMap.Point(100.6,36.202696), 5);
  		map.addControl(new BMap.NavigationControl());

		for (i in datas) {
			var lats = datas[i].lats.split(',');		
			var lons = datas[i].lons.split(',');		
			var points   = [];

			for (j in lons) {
				var tmp_lon = lons[j];
				var tmp_lat = lats[j];

				points.push(new BMap.Point(tmp_lon, tmp_lat));
			}

			if (points) {
				var polyline = new BMap.Polyline(points, {strokeColor:"red", strokeWeight:6, strokeOpacity:0.5});  //定义折线
			}

			console.log(points);
			map.addOverlay(polyline);     //添加折线到地图上
		}
	});
}

prepareData ();
</script>
